feat: Add package installation checks and neovim installation

diff --git a/home/run_once_before_add-pkgs-deb-ubu.sh.tmpl b/home/run_once_before_add-pkgs-deb-ubu.sh.tmpl
--- a/home/run_once_before_add-pkgs-deb-ubu.sh.tmpl
+++ b/home/run_once_before_add-pkgs-deb-ubu.sh.tmpl
@@ -8,11 +8,34 @@ sudo -v
 
 # Install general packages
 sudo apt update
-sudo apt install -y neovim zoxide fzf curl wget net-tools zsh git tmux gpg ripgrep gcc
 
-# Install nvim(>=v0.10.0)
-wget -P ${HOME}/.local/bin https://github.com/neovim/neovim/releases/download/v0.10.0/nvim-linux64.tar.gz
-tar xzf ${HOME}/.local/bin/nvim-linux64.tar.gz -C ${HOME}/.local/bin
+packages=("zoxide" "fzf" "curl" "wget" "net-tools" "zsh" "git" "tmux" "gpg" "ripgrep" "gcc")
+
+for package in "${packages[@]}"; do
+    if ! dpkg -l | grep -q "^ii  $package"; then
+        echo "Installing $package..."
+        sudo apt install -y $package
+    else
+        echo "$package is already installed."
+    fi
+done
+
+# Install nvim(v0.10.0)
+if ! command -v nvim &> /dev/null; then
+    echo "Neovim is not installed. Installing Neovim v0.10.0..."
+    wget -P ${HOME}/.local/bin https://github.com/neovim/neovim/releases/download/v0.10.0/nvim-linux64.tar.gz
+    tar xzf ${HOME}/.local/bin/nvim-linux64.tar.gz -C ${HOME}/.local/bin
+
+    if command -v nvim &> /dev/null; then
+        echo "Neovim v0.10.0 installed successfully."
+        rm ${HOME}/.local/bin/nvim-linux64.tar.gz
+        echo "Downloaded tar.gz file removed."
+    else
+        echo "Neovim installation failed."
+    fi
+else
+    echo "Neovim is already installed."
+fi
 
 # Install TPM
 if command -v tmux &> /dev/null; then
@@ -22,13 +45,13 @@ if command -v tmux &> /dev/null; then
 fi
 
 # Install eza
-if ! apt-key list | grep -q gierens; then
-    sudo mkdir -p /etc/apt/keyrings
-    wget -qO- https://raw.githubusercontent.com/eza-community/eza/main/deb.asc | sudo gpg --dearmor -o /etc/apt/keyrings/gierens.gpg
-    echo "deb [signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main" | sudo tee /etc/apt/sources.list.d/gierens.list
-    sudo chmod 644 /etc/apt/keyrings/gierens.gpg /etc/apt/sources.list.d/gierens.list
-    sudo apt update
-    sudo apt install -y eza
+if [ ! -f "/usr/bin/eza" ]; then
+  sudo mkdir -p /etc/apt/keyrings
+  wget -qO- https://raw.githubusercontent.com/eza-community/eza/main/deb.asc | sudo gpg --dearmor -o /etc/apt/keyrings/gierens.gpg
+  echo "deb [signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main" | sudo tee /etc/apt/sources.list.d/gierens.list
+  sudo chmod 644 /etc/apt/keyrings/gierens.gpg /etc/apt/sources.list.d/gierens.list
+  sudo apt update
+  sudo apt install -y eza
 fi
 
 # Install tailscale
@@ -39,7 +62,7 @@ else
 fi
 
 # Install Starship
-if [ ! -f "${HOME}/.local/bin/starship" ]; then
+if [ ! -f "/usr/local/bin/starship" ]; then
     curl -sS https://starship.rs/install.sh | sh -s -- -y
 fi
 
